### ISSUE TITLE
Type 'select' doesn`t work

### ISSUE THREAD

**Issue by abada** [FokkeZB/nl.fokkezb.form#19]
When i try the test app on my android device , type `select` not working ! just nothing happened when try change value .

I tried run on SDK `5.2.0.GA` , `5.2.1.GA`

**Comment by FokkeZB** [comment]
That could very well be since Android support is still in beta (see #18).

@HazemKhaled could you have a look?

**Comment by abada** [comment]
ooh beta ! , ok and i will try to see what is the problem

**Comment by HazemKhaled** [comment]
Just saw this issue right now, @abada this will fix #24

**Comment by abada** [comment]
👍

**Comment by FokkeZB** [comment]
Assuming @HazemKhaled means "will fixed in" :D
