### ISSUE TITLE
Multiple select types, shows the last select options for all select type fields

### ISSUE THREAD

**Issue by locactus** [FokkeZB/nl.fokkezb.form#20]
Hi not sure if it's something I'm doing but I also ran the test example and noticed the same issue.
If you have more than one select field the options shown for both are the same, always the last defined select field options get shown.

**Comment by FokkeZB** [comment]
Thanks @locactus, that was a stupid bug. Fixed it in 1.8.1!

**Comment by locactus** [comment]
@FokkeZB  Hey thanks for the fix. You can't have software without a few bugs here and there :)
