### ISSUE TITLE
More Android issues

### ISSUE THREAD

**Issue by HazemKhaled** [FokkeZB/nl.fokkezb.form#23]
I'm continue working on Android support:

- [x] FIX: Layout vertical and horizontal for the row
- [x] FIX: Date picker
- [x] FIX: Add support for optionDialog option

**Comment by FokkeZB** [comment]
You rock @HazemKhaled! 🎸

**Comment by HazemKhaled** [comment]
@FokkeZB do you think this is a Titanium bug? any workaround in your mind?
https://archive.appcelerator.com/question/159923/cant-show-timepickerdialog-on-top-of-window-with-titanium-3

**Comment by HazemKhaled** [comment]
In case we np think to do with time picker, check the pull request and accept it please, Thanks 👍

**Comment by HazemKhaled** [comment]
I'll separate time picker issue on Android in another issue to close this one

**Comment by FokkeZB** [comment]
You rock!
