### ISSUE TITLE
test doesn't work

### ISSUE THREAD

**Issue by rmuzzi** [FokkeZB/nl.fokkezb.form#7]
I wanted to try the test branch but it doesn't seem to work. When i run grunt, it says:

[ERROR] widget "nl.fokkezb.form" view "widget" does not exist.
[ERROR] The following paths were inspected:
[ERROR] /Users/rmu/Downloads/nl.fokkezb.form-test/app/widgets/nl.fokkezb.form/views/ios/widget
[ERROR] /Users/rmu/Downloads/nl.fokkezb.form-test/app/widgets/nl.fokkezb.form/views/widget
[ERROR] /usr/local/lib/node_modules/alloy/widgets/nl.fokkezb.form/views/ios/widget
[ERROR] /usr/local/lib/node_modules/alloy/widgets/nl.fokkezb.form/views/widget
[ERROR] Alloy compiler failed

Am I doing smth wrong?

**Comment by rmuzzi** [comment]
but this happens only if i copy the widget folder on my own. otherwise this happens:

[DEBUG] ----- CLEANING RESOURCES -----
[ERROR] config.json references non-existent widgets: ["nl.fokkezb.form"]
[ERROR] If you are not using these widgets, remove them from your config.json dependencies.
[ERROR] If you are using them, add them to your project's widget folder.
[ERROR] Alloy compiler failed

**Comment by FokkeZB** [comment]
Did you follow the instructions that the master branch should be checked out in a "master" folder on the same level as where you checked out the "test" branch?
